services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env.backend
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: cosmetic-postgres
    env_file:
      - .env.db
    ports:
      - "5435:5432"
    volumes:
      - cosmetic_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cosmetic_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app-network

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    env_file:
      - .env.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      additional_contexts:
        frontend_src: ./frontend
    container_name: nginx
    depends_on:
      - backend
      - minio
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

volumes:
  cosmetic_pgdata:
  minio_data:

networks:
  app-network: