// <auto-generated />
using System;
using CosmeticEnterpriseBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CosmeticEnterpriseBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423175350_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProductImages", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdFinishedProduct")
                        .HasColumnType("bigint")
                        .HasColumnName("id_finished_product");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("object_key");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("IdFinishedProduct")
                        .HasDatabaseName("IX_product_images_id_finished_product");

                    b.HasIndex("IdFinishedProduct", "IsMain")
                        .IsUnique()
                        .HasDatabaseName("IX_product_images_id_finished_product_is_main")
                        .HasFilter("\"is_main\" = true");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProducts", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdProductCategory")
                        .HasColumnType("bigint")
                        .HasColumnName("id_product_category");

                    b.Property<long>("IdRecipe")
                        .HasColumnType("bigint")
                        .HasColumnName("id_recipe");

                    b.Property<long>("IdUnitsOfMeasurement")
                        .HasColumnType("bigint")
                        .HasColumnName("id_units_of_measurement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("IdProductCategory")
                        .HasDatabaseName("IX_finished_products_id_product_category");

                    b.HasIndex("IdRecipe")
                        .HasDatabaseName("IX_finished_products_id_recipe");

                    b.HasIndex("IdUnitsOfMeasurement")
                        .HasDatabaseName("IX_finished_products_id_units_of_measurement");

                    b.ToTable("finished_products", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.LeftoversInWarehouses", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdFinishedProduct")
                        .HasColumnType("bigint")
                        .HasColumnName("id_finished_product");

                    b.Property<long>("IdWarehouse")
                        .HasColumnType("bigint")
                        .HasColumnName("id_warehouse");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.Property<int>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_quantity");

                    b.HasKey("Id");

                    b.HasIndex("IdFinishedProduct")
                        .HasDatabaseName("IX_leftovers_in_warehouses_id_finished_product");

                    b.HasIndex("IdWarehouse")
                        .HasDatabaseName("IX_leftovers_in_warehouses_id_warehouse");

                    b.ToTable("leftovers_in_warehouses", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Materials", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdUnitsOfMeasurement")
                        .HasColumnType("bigint")
                        .HasColumnName("id_units_of_measurement");

                    b.HasKey("Id");

                    b.HasIndex("IdUnitsOfMeasurement")
                        .HasDatabaseName("IX_materials_id_units_of_measurement");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.OrderItems", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdFinishedProduct")
                        .HasColumnType("bigint")
                        .HasColumnName("id_finished_product");

                    b.Property<long>("IdOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("id_order");

                    b.Property<decimal>("LineTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("line_total");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("IdFinishedProduct")
                        .HasDatabaseName("IX_order_items_id_finished_product");

                    b.HasIndex("IdOrder")
                        .HasDatabaseName("IX_order_items_id_order");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Orders", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("DeliveryPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("delivery_price");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("delivery_status");

                    b.Property<long>("IdSalesChannel")
                        .HasColumnType("bigint")
                        .HasColumnName("id_sales_channel");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<long>("IdUserAddress")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user_address");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_status");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_status");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_type");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("IdSalesChannel")
                        .HasDatabaseName("IX_orders_id_sales_channel");

                    b.HasIndex("IdUser")
                        .HasDatabaseName("IX_orders_id_user");

                    b.HasIndex("IdUserAddress")
                        .HasDatabaseName("IX_orders_id_user_address");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductCategories", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_product_categories_name");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductParties", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdFinishedProduct")
                        .HasColumnType("bigint")
                        .HasColumnName("id_finished_product");

                    b.HasKey("Id");

                    b.HasIndex("IdFinishedProduct")
                        .HasDatabaseName("IX_product_parties_id_finished_product");

                    b.ToTable("product_parties", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Recipes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_recipes_name");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SalesChannels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_sales_channels_name");

                    b.ToTable("sales_channels", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ShoppingCart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("IdUser")
                        .IsUnique()
                        .HasDatabaseName("IX_shopping_carts_id_user");

                    b.ToTable("shopping_carts", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ShoppingCartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("IdFinishedProduct")
                        .HasColumnType("bigint")
                        .HasColumnName("id_finished_product");

                    b.Property<long>("IdShoppingCart")
                        .HasColumnType("bigint")
                        .HasColumnName("id_shopping_cart");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("IdFinishedProduct")
                        .HasDatabaseName("IX_shopping_cart_items_id_finished_product");

                    b.HasIndex("IdShoppingCart", "IdFinishedProduct")
                        .IsUnique()
                        .HasDatabaseName("IX_shopping_cart_items_id_shopping_cart_id_finished_product");

                    b.ToTable("shopping_cart_items", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Suppliers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdSupplier")
                        .HasColumnType("bigint")
                        .HasColumnName("id_supplier");

                    b.HasKey("Id");

                    b.HasIndex("IdSupplier")
                        .HasDatabaseName("IX_supplies_from_suppliers_id_supplier");

                    b.ToTable("supplies_from_suppliers", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SupplyPositions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdMaterial")
                        .HasColumnType("bigint")
                        .HasColumnName("id_material");

                    b.Property<long>("IdSuppliesFromSupplier")
                        .HasColumnType("bigint")
                        .HasColumnName("id_supplies_from_supplier");

                    b.HasKey("Id");

                    b.HasIndex("IdMaterial")
                        .HasDatabaseName("IX_supply_positions_id_material");

                    b.HasIndex("IdSuppliesFromSupplier")
                        .HasDatabaseName("IX_supply_positions_id_supplies_from_supplier");

                    b.ToTable("supply_positions", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_units_of_measurement_name");

                    b.ToTable("units_of_measurement", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.User", b =>
                {
                    b.Property<long>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdUser"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UserAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apartment")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apartment");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("house");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("street");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("IdUser")
                        .HasDatabaseName("IX_user_addresses_id_user");

                    b.ToTable("user_addresses", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UserRefreshToken", b =>
                {
                    b.Property<long>("IdUserRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdUserRefreshToken"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text")
                        .HasColumnName("created_by_ip");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text")
                        .HasColumnName("revoked_by_ip");

                    b.HasKey("IdUserRefreshToken");

                    b.HasIndex("IdUser")
                        .HasDatabaseName("IX_user_refresh_tokens_id_user");

                    b.ToTable("user_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Warehouses", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProductImages", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProduct")
                        .WithMany("Images")
                        .HasForeignKey("IdFinishedProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProduct");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProducts", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.ProductCategories", "ProductCategories")
                        .WithMany("FinishedProductsList")
                        .HasForeignKey("IdProductCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.Recipes", "Recipe")
                        .WithMany("FinishedProductsList")
                        .HasForeignKey("IdRecipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", "UnitsOfMeasurement")
                        .WithMany("FinishedProductsList")
                        .HasForeignKey("IdUnitsOfMeasurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategories");

                    b.Navigation("Recipe");

                    b.Navigation("UnitsOfMeasurement");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.LeftoversInWarehouses", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProducts")
                        .WithMany("LeftoversInWarehousesList")
                        .HasForeignKey("IdFinishedProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.Warehouses", "Warehouses")
                        .WithMany("LeftoversInWarehousesList")
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProducts");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Materials", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", "UnitsOfMeasurement")
                        .WithMany("MaterialsList")
                        .HasForeignKey("IdUnitsOfMeasurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitsOfMeasurement");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.OrderItems", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProducts")
                        .WithMany("OrderItemsList")
                        .HasForeignKey("IdFinishedProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.Orders", "Order")
                        .WithMany("OrderItemsList")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProducts");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Orders", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.SalesChannels", "SalesChannel")
                        .WithMany("OrdersList")
                        .HasForeignKey("IdSalesChannel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.UserAddress", "UserAddress")
                        .WithMany("Orders")
                        .HasForeignKey("IdUserAddress")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalesChannel");

                    b.Navigation("User");

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductParties", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProducts")
                        .WithMany("ProductPartiesList")
                        .HasForeignKey("IdFinishedProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProducts");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ShoppingCart", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ShoppingCartItem", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProduct")
                        .WithMany()
                        .HasForeignKey("IdFinishedProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.ShoppingCart", "ShoppingCart")
                        .WithMany("Items")
                        .HasForeignKey("IdShoppingCart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProduct");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.Suppliers", "Supplier")
                        .WithMany("SuppliesFromSuppliersList")
                        .HasForeignKey("IdSupplier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SupplyPositions", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.Materials", "Material")
                        .WithMany("SupplyPositionsList")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", "SuppliesFromSuppliers")
                        .WithMany("SupplyPositionsList")
                        .HasForeignKey("IdSuppliesFromSupplier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("SuppliesFromSuppliers");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UserAddress", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProducts", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("LeftoversInWarehousesList");

                    b.Navigation("OrderItemsList");

                    b.Navigation("ProductPartiesList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Materials", b =>
                {
                    b.Navigation("SupplyPositionsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Orders", b =>
                {
                    b.Navigation("OrderItemsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductCategories", b =>
                {
                    b.Navigation("FinishedProductsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Recipes", b =>
                {
                    b.Navigation("FinishedProductsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SalesChannels", b =>
                {
                    b.Navigation("OrdersList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ShoppingCart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Suppliers", b =>
                {
                    b.Navigation("SuppliesFromSuppliersList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", b =>
                {
                    b.Navigation("SupplyPositionsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", b =>
                {
                    b.Navigation("FinishedProductsList");

                    b.Navigation("MaterialsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UserAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Warehouses", b =>
                {
                    b.Navigation("LeftoversInWarehousesList");
                });
#pragma warning restore 612, 618
        }
    }
}
