// <auto-generated />
using System;
using CosmeticEnterpriseBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CosmeticEnterpriseBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314151454_AddColumnNameInFinishedProducts")]
    partial class AddColumnNameInFinishedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Customers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProducts", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProductCategoriesId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitsOfMeasurementId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoriesId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitsOfMeasurementId");

                    b.ToTable("finished_products", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.LeftoversInWarehouses", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FinishedProductsId")
                        .HasColumnType("bigint");

                    b.Property<long>("WarehousesId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FinishedProductsId");

                    b.HasIndex("WarehousesId");

                    b.ToTable("leftovers_in_warehouses", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Materials", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("UnitsOfMeasurementId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UnitsOfMeasurementId");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.OrderItems", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FinishedProductsId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FinishedProductsId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.OrderStatuses", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("order_statuses", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Orders", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdCustomers")
                        .HasColumnType("bigint")
                        .HasColumnName("IdCustomers");

                    b.Property<long>("IdOrderStatuses")
                        .HasColumnType("bigint")
                        .HasColumnName("IdOrderStatuses");

                    b.Property<long>("IdSalesChannels")
                        .HasColumnType("bigint")
                        .HasColumnName("IdSalesChannels");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomers");

                    b.HasIndex("IdOrderStatuses");

                    b.HasIndex("IdSalesChannels");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductCategories", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductParties", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FinishedProductsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FinishedProductsId");

                    b.ToTable("product_parties", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Recipes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SalesChannels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("sales_channels", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Suppliers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("supplies_from_suppliers", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SupplyPositions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<long>("SuppliesFromSuppliersId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SuppliesFromSuppliersId");

                    b.ToTable("supply_positions", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("units_of_measurement", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.User", b =>
                {
                    b.Property<long>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdUser"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UserRefreshToken", b =>
                {
                    b.Property<long>("IdUserRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdUserRefreshToken"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.HasKey("IdUserRefreshToken");

                    b.HasIndex("IdUser");

                    b.ToTable("user_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Warehouses", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProducts", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.ProductCategories", "ProductCategories")
                        .WithMany("FinishedProductsList")
                        .HasForeignKey("ProductCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.Recipes", "Recipe")
                        .WithMany("FinishedProductsList")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", "UnitsOfMeasurement")
                        .WithMany("FinishedProductsList")
                        .HasForeignKey("UnitsOfMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategories");

                    b.Navigation("Recipe");

                    b.Navigation("UnitsOfMeasurement");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.LeftoversInWarehouses", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProducts")
                        .WithMany("LeftoversInWarehousesList")
                        .HasForeignKey("FinishedProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.Warehouses", "Warehouses")
                        .WithMany("LeftoversInWarehousesList")
                        .HasForeignKey("WarehousesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProducts");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Materials", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", "UnitsOfMeasurement")
                        .WithMany("MaterialsList")
                        .HasForeignKey("UnitsOfMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitsOfMeasurement");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.OrderItems", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProducts")
                        .WithMany("OrderItemsList")
                        .HasForeignKey("FinishedProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.Orders", "Order")
                        .WithMany("LstOrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProducts");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Orders", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.Customers", "Customer")
                        .WithMany("LstOrders")
                        .HasForeignKey("IdCustomers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.OrderStatuses", "OrderStatus")
                        .WithMany("LstOrders")
                        .HasForeignKey("IdOrderStatuses")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.SalesChannels", "SalesChannel")
                        .WithMany("LstOrders")
                        .HasForeignKey("IdSalesChannels")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("OrderStatus");

                    b.Navigation("SalesChannel");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductParties", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProducts")
                        .WithMany("ProductPartiesList")
                        .HasForeignKey("FinishedProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProducts");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.Suppliers", "Supplier")
                        .WithMany("SuppliesFromSuppliersList")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SupplyPositions", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.Materials", "Material")
                        .WithMany("SupplyPositionsList")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", "SuppliesFromSuppliers")
                        .WithMany("SupplyPositionsList")
                        .HasForeignKey("SuppliesFromSuppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("SuppliesFromSuppliers");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Customers", b =>
                {
                    b.Navigation("LstOrders");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProducts", b =>
                {
                    b.Navigation("LeftoversInWarehousesList");

                    b.Navigation("OrderItemsList");

                    b.Navigation("ProductPartiesList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Materials", b =>
                {
                    b.Navigation("SupplyPositionsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.OrderStatuses", b =>
                {
                    b.Navigation("LstOrders");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Orders", b =>
                {
                    b.Navigation("LstOrderItems");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductCategories", b =>
                {
                    b.Navigation("FinishedProductsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Recipes", b =>
                {
                    b.Navigation("FinishedProductsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SalesChannels", b =>
                {
                    b.Navigation("LstOrders");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Suppliers", b =>
                {
                    b.Navigation("SuppliesFromSuppliersList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", b =>
                {
                    b.Navigation("SupplyPositionsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", b =>
                {
                    b.Navigation("FinishedProductsList");

                    b.Navigation("MaterialsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Warehouses", b =>
                {
                    b.Navigation("LeftoversInWarehousesList");
                });
#pragma warning restore 612, 618
        }
    }
}
