// <auto-generated />
using System;
using CosmeticEnterpriseBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CosmeticEnterpriseBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Customers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProductImages", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdFinishedProduct")
                        .HasColumnType("bigint")
                        .HasColumnName("id_finished_product");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("object_key");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("IdFinishedProduct");

                    b.HasIndex("IdFinishedProduct", "IsMain")
                        .IsUnique()
                        .HasFilter("\"is_main\" = true");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProducts", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdProductCategory")
                        .HasColumnType("bigint")
                        .HasColumnName("id_product_category");

                    b.Property<long>("IdRecipe")
                        .HasColumnType("bigint")
                        .HasColumnName("id_recipe");

                    b.Property<long>("IdUnitsOfMeasurement")
                        .HasColumnType("bigint")
                        .HasColumnName("id_units_of_measurement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdProductCategory");

                    b.HasIndex("IdRecipe");

                    b.HasIndex("IdUnitsOfMeasurement");

                    b.ToTable("finished_products", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.LeftoversInWarehouses", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdFinishedProduct")
                        .HasColumnType("bigint")
                        .HasColumnName("id_finished_product");

                    b.Property<long>("IdWarehouse")
                        .HasColumnType("bigint")
                        .HasColumnName("id_warehouse");

                    b.HasKey("Id");

                    b.HasIndex("IdFinishedProduct");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("leftovers_in_warehouses", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Materials", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdUnitsOfMeasurement")
                        .HasColumnType("bigint")
                        .HasColumnName("id_units_of_measurement");

                    b.HasKey("Id");

                    b.HasIndex("IdUnitsOfMeasurement");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.OrderItems", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdFinishedProduct")
                        .HasColumnType("bigint")
                        .HasColumnName("id_finished_product");

                    b.Property<long>("IdOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("id_order");

                    b.HasKey("Id");

                    b.HasIndex("IdFinishedProduct");

                    b.HasIndex("IdOrder");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.OrderStatuses", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("order_statuses", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Orders", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdCustomer")
                        .HasColumnType("bigint")
                        .HasColumnName("id_customer");

                    b.Property<long>("IdOrderStatus")
                        .HasColumnType("bigint")
                        .HasColumnName("id_order_status");

                    b.Property<long>("IdSalesChannel")
                        .HasColumnType("bigint")
                        .HasColumnName("id_sales_channel");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdOrderStatus");

                    b.HasIndex("IdSalesChannel");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductCategories", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductParties", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdFinishedProduct")
                        .HasColumnType("bigint")
                        .HasColumnName("id_finished_product");

                    b.HasKey("Id");

                    b.HasIndex("IdFinishedProduct");

                    b.ToTable("product_parties", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Recipes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SalesChannels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("sales_channels", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Suppliers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdSupplier")
                        .HasColumnType("bigint")
                        .HasColumnName("id_supplier");

                    b.HasKey("Id");

                    b.HasIndex("IdSupplier");

                    b.ToTable("supplies_from_suppliers", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SupplyPositions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdMaterial")
                        .HasColumnType("bigint")
                        .HasColumnName("id_material");

                    b.Property<long>("IdSuppliesFromSupplier")
                        .HasColumnType("bigint")
                        .HasColumnName("id_supplies_from_supplier");

                    b.HasKey("Id");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdSuppliesFromSupplier");

                    b.ToTable("supply_positions", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("units_of_measurement", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.User", b =>
                {
                    b.Property<long>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdUser"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UserRefreshToken", b =>
                {
                    b.Property<long>("IdUserRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdUserRefreshToken"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.HasKey("IdUserRefreshToken");

                    b.HasIndex("IdUser");

                    b.ToTable("user_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Warehouses", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProductImages", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProduct")
                        .WithMany("Images")
                        .HasForeignKey("IdFinishedProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProduct");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProducts", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.ProductCategories", "ProductCategories")
                        .WithMany("FinishedProductsList")
                        .HasForeignKey("IdProductCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.Recipes", "Recipe")
                        .WithMany("FinishedProductsList")
                        .HasForeignKey("IdRecipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", "UnitsOfMeasurement")
                        .WithMany("FinishedProductsList")
                        .HasForeignKey("IdUnitsOfMeasurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategories");

                    b.Navigation("Recipe");

                    b.Navigation("UnitsOfMeasurement");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.LeftoversInWarehouses", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProducts")
                        .WithMany("LeftoversInWarehousesList")
                        .HasForeignKey("IdFinishedProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.Warehouses", "Warehouses")
                        .WithMany("LeftoversInWarehousesList")
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProducts");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Materials", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", "UnitsOfMeasurement")
                        .WithMany("MaterialsList")
                        .HasForeignKey("IdUnitsOfMeasurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitsOfMeasurement");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.OrderItems", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProducts")
                        .WithMany("OrderItemsList")
                        .HasForeignKey("IdFinishedProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.Orders", "Order")
                        .WithMany("OrderItemsList")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProducts");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Orders", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.Customers", "Customer")
                        .WithMany("OrdersList")
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.OrderStatuses", "OrderStatus")
                        .WithMany("OrdersList")
                        .HasForeignKey("IdOrderStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.SalesChannels", "SalesChannel")
                        .WithMany("OrdersList")
                        .HasForeignKey("IdSalesChannel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("OrderStatus");

                    b.Navigation("SalesChannel");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductParties", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.FinishedProducts", "FinishedProducts")
                        .WithMany("ProductPartiesList")
                        .HasForeignKey("IdFinishedProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedProducts");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.Suppliers", "Supplier")
                        .WithMany("SuppliesFromSuppliersList")
                        .HasForeignKey("IdSupplier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SupplyPositions", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.Materials", "Material")
                        .WithMany("SupplyPositionsList")
                        .HasForeignKey("IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", "SuppliesFromSuppliers")
                        .WithMany("SupplyPositionsList")
                        .HasForeignKey("IdSuppliesFromSupplier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("SuppliesFromSuppliers");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("CosmeticEnterpriseBack.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Customers", b =>
                {
                    b.Navigation("OrdersList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.FinishedProducts", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("LeftoversInWarehousesList");

                    b.Navigation("OrderItemsList");

                    b.Navigation("ProductPartiesList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Materials", b =>
                {
                    b.Navigation("SupplyPositionsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.OrderStatuses", b =>
                {
                    b.Navigation("OrdersList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Orders", b =>
                {
                    b.Navigation("OrderItemsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.ProductCategories", b =>
                {
                    b.Navigation("FinishedProductsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Recipes", b =>
                {
                    b.Navigation("FinishedProductsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SalesChannels", b =>
                {
                    b.Navigation("OrdersList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Suppliers", b =>
                {
                    b.Navigation("SuppliesFromSuppliersList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.SuppliesFromSuppliers", b =>
                {
                    b.Navigation("SupplyPositionsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.UnitsOfMeasurement", b =>
                {
                    b.Navigation("FinishedProductsList");

                    b.Navigation("MaterialsList");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CosmeticEnterpriseBack.Entities.Warehouses", b =>
                {
                    b.Navigation("LeftoversInWarehousesList");
                });
#pragma warning restore 612, 618
        }
    }
}
